"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockIndustries = void 0;
exports.mockIndustries = [
    {
        id: 'ind-1',
        title: 'Automotive',
        slug: 'automotive',
        summary: 'Technology solutions supporting automotive manufacturers, testing facilities, and service providers.',
        description: 'The automotive industry demands precision, reliability, and efficiency at every stage from manufacturing to after-sales service. Vtest delivers integrated software and hardware solutions that support automotive testing, quality assurance, and operational management.',
        image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=80',
        icon: 'Car',
        status: 'PUBLISHED',
        challenges: [
            {
                title: 'Quality Consistency',
                description: 'Maintaining consistent quality standards across multiple production lines and testing stations.',
            },
            {
                title: 'Compliance Complexity',
                description: 'Meeting evolving regulatory requirements across different markets and vehicle types.',
            },
            {
                title: 'Equipment Diversity',
                description: 'Managing diverse test equipment from multiple manufacturers in integrated workflows.',
            },
            {
                title: 'Data Management',
                description: 'Capturing, storing, and analysing large volumes of test and inspection data effectively.',
            },
        ],
        vtestCapabilities: [
            'End-of-line testing automation',
            'Multi-equipment integration',
            'Quality data capture and analytics',
            'Compliance and traceability documentation',
            'Production system integration',
        ],
        useCases: [
            'Final assembly quality testing',
            'Brake and emissions testing integration',
            'Component validation testing',
            'Warranty and recall data management',
        ],
        relatedSolutionIds: ['sol-2', 'sol-4'],
        relatedProductIds: ['prod-hw-2', 'prod-sw-3'],
        technologies: ['VtestSense Module', 'VtestConnect', 'VtestAnalytics'],
        seoTitle: 'Automotive Industry Solutions | Vtest',
        seoDescription: 'Technology solutions for automotive manufacturers and testing facilities. End-of-line testing, equipment integration, quality analytics.',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'ind-2',
        title: 'Vehicle Testing',
        slug: 'vehicle-testing',
        summary: 'Comprehensive technology for vehicle testing stations, inspection centers, and testing authorities.',
        description: 'Vehicle testing organizations require reliable, scalable technology to manage inspection workflows, equipment, and compliance across single and multi-site operations. Vtest provides purpose-built solutions for the unique demands of the vehicle testing sector.',
        image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=1200&q=80',
        icon: 'ClipboardCheck',
        status: 'PUBLISHED',
        challenges: [
            {
                title: 'Workflow Digitization',
                description: 'Transitioning from paper-based to fully digital inspection processes reliably.',
            },
            {
                title: 'Multi-Lane Coordination',
                description: 'Coordinating operations across multiple inspection lanes simultaneously.',
            },
            {
                title: 'Equipment Reliability',
                description: 'Ensuring test equipment operates reliably in continuous, high-throughput environments.',
            },
        ],
        vtestCapabilities: [
            'Digital inspection workflow management',
            'Multi-lane operational control',
            'Equipment integration and automation',
            'Compliance and certification management',
            'Operational analytics and reporting',
        ],
        useCases: [
            'Periodic vehicle inspection management',
            'Multi-lane testing station operations',
            'Equipment lifecycle management',
            'Inspector performance and quality monitoring',
        ],
        relatedSolutionIds: ['sol-1', 'sol-3', 'sol-5'],
        relatedProductIds: ['prod-sw-1', 'prod-hw-1'],
        technologies: ['VtestIMS', 'VtestLane Controller', 'VtestAnalytics'],
        seoTitle: 'Vehicle Testing Industry Solutions | Vtest',
        seoDescription: 'Purpose-built technology for vehicle testing stations and inspection centers. Digital workflows, lane management, equipment integration, compliance reporting.',
        createdAt: '2024-01-05T00:00:00Z',
        updatedAt: '2024-06-05T00:00:00Z',
    },
    {
        id: 'ind-3',
        title: 'Government / Transport',
        slug: 'government-transport',
        summary: 'Technology platforms for government transport authorities and regulatory bodies managing vehicle compliance programs.',
        description: 'Government transport authorities and regulatory bodies require robust, auditable technology to manage vehicle compliance programs at scale. Vtest provides solutions designed for the accountability, security, and scalability requirements of public-sector applications.',
        image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&q=80',
        icon: 'Building2',
        status: 'PUBLISHED',
        challenges: [
            {
                title: 'Regulatory Accountability',
                description: 'Maintaining complete audit trails for all inspection activities and decisions.',
            },
            {
                title: 'Scale and Reliability',
                description: 'Operating reliably at national or regional scale with high availability requirements.',
            },
            {
                title: 'Interoperability',
                description: 'Integrating with diverse existing government IT systems and databases.',
            },
        ],
        vtestCapabilities: [
            'Audit-grade compliance management',
            'Scalable inspection management platform',
            'Government system integration capabilities',
            'Secure data management',
            'Regulatory reporting and analytics',
        ],
        useCases: [
            'National vehicle roadworthiness programs',
            'Transport authority compliance management',
            'Multi-site inspection network management',
        ],
        relatedSolutionIds: ['sol-1', 'sol-5'],
        relatedProductIds: ['prod-sw-1', 'prod-sw-2'],
        technologies: ['VtestIMS', 'VtestAnalytics', 'Secure integration'],
        seoTitle: 'Government & Transport Solutions | Vtest',
        seoDescription: 'Technology solutions for government transport authorities. Audit-grade compliance management, scalable inspection platforms, regulatory reporting.',
        createdAt: '2024-01-08T00:00:00Z',
        updatedAt: '2024-06-08T00:00:00Z',
    },
    {
        id: 'ind-4',
        title: 'Manufacturing',
        slug: 'manufacturing',
        summary: 'Precision testing and quality assurance technology for manufacturing facilities with automated test requirements.',
        description: 'Manufacturing facilities require reliable automated testing to ensure product quality, traceability, and production efficiency. Vtest provides hardware and software solutions that integrate into manufacturing workflows to deliver consistent, automated quality assurance.',
        image: 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1200&q=80',
        icon: 'Factory',
        status: 'PUBLISHED',
        challenges: [
            {
                title: 'Production Speed',
                description: 'Testing must keep pace with production line speeds without creating bottlenecks.',
            },
            {
                title: 'Traceability',
                description: 'Full traceability from test results to individual production units is required.',
            },
            {
                title: 'System Integration',
                description: 'Test systems must integrate with MES, ERP, and quality management systems.',
            },
        ],
        vtestCapabilities: [
            'High-speed automated test sequences',
            'Precision measurement and data capture',
            'Production system integration (MES/ERP)',
            'Traceability and quality records',
            'Statistical process control support',
        ],
        useCases: [
            'Vehicle end-of-line testing',
            'Component quality verification',
            'Production quality audits',
            'Supplier quality management',
        ],
        relatedSolutionIds: ['sol-2', 'sol-4'],
        relatedProductIds: ['prod-hw-2', 'prod-sw-3'],
        technologies: ['VtestSense Module', 'VtestConnect', 'Production integration'],
        seoTitle: 'Manufacturing Industry Solutions | Vtest',
        seoDescription: 'Precision testing and quality assurance technology for manufacturing. Automated test sequences, traceability, production system integration.',
        createdAt: '2024-01-10T00:00:00Z',
        updatedAt: '2024-06-10T00:00:00Z',
    },
];
